#In production server port can be changed to 0 to enable load balancing by the eureka discovery server
server:
  port: 8085

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    hostname: localhost
    prefer-ip-address: true

management:
  zipkin:
    tracing:
      endpoint: http://localhost:9411/api/v2/spans
  tracing:
    sampling:
      probability: 1.0
  health:
    circuitbreakers:
      enabled: true

spring:
  application:
    name: book-inventory
    config:
      book_inventory-url: http://localhost:8222/api/v1/book-inventory
  boot:
    admin:
      client:
        instance:
          management-base-url: http://localhost:8085
  elasticsearch:
    rest:
      uris: http://localhost:9200
  data:
    elasticsearch:
      cluster-name: docker-cluster
      repository:
        enabled: true
  jackson:
    default-property-inclusion: non_null
  redis:
    host: localhost
    port: 6379
  cache:
    type: redis
    redis:
      key-prefix: books

