server:
  port: 8086

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    hostname: localhost
    prefer-ip-address: true

management:
  tracing:
    sampling:
      probability: 1.0
  endpoints:
    web:
      exposure:
        include: "*"

spring:
  application:
    name: payment-service
    config:
    payment_service-url: http://localhost:8222/api/v1/payment-service
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/payment_db
    username: postgres
    password: password
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  boot:
    admin:
      client:
        instance:
        management-base-url: http://localhost:8086/
  redis:
    host: localhost
    port: 6379
  cache:
    type: redis
    redis:
      key-prefix: payments

# Flyway configuration
flyway:
  locations: classpath:db/migration
  baseline-on-migrate: true # Baseline on migrate if no schema history table exists